# Holdings Provider - Load, join, and return enriched holding data

SEED_HOLDINGS = [
    {
        "County_Name": "Castellon",
        "Barony_Name": "Castello",
        "Holding_Type": "Castle",
        "Duchy_Name": "Balan",
        "Terrain_Type": "domain",
        "Status": "domain",
        "Control": 15,
        "Development": 8,
        "Tax": 0.03,
        "Levies": 63,
        "Buildings_Count": 0,
        "Open_Building_Slots": 0,
        "Special": False,
    },
    {
        "County_Name": "Castellon",
        "Barony_Name": "Segorbe",
        "Holding_Type": "Temple",
        "Duchy_Name": "Balan",
        "Terrain_Type": "leased",
        "Status": "leased",
        "Control": 15,
        "Development": 8,
        "Tax": 0.0,
        "Levies": 30,
        "Buildings_Count": 0,
        "Open_Building_Slots": 0,
        "Special": False,
    },
    {
        "County_Name": "Castellon",
        "Barony_Name": "Amposta",
        "Holding_Type": "City",
        "Duchy_Name": "Balan",
        "Terrain_Type": "vassal",
        "Status": "vassal",
        "Control": 15,
        "Development": 8,
        "Tax": 0.0,
        "Levies": 44,
        "Buildings_Count": 0,
        "Open_Building_Slots": 0,
        "Special": False,
    },
    {
        "County_Name": "Bejaia",
        "Barony_Name": "Bejaia",
        "Holding_Type": "Castle",
        "Duchy_Name": "Drylands",
        "Terrain_Type": "domain",
        "Status": "domain",
        "Control": 100,
        "Development": 8,
        "Tax": 0.82,
        "Levies": 109,
        "Buildings_Count": 0,
        "Open_Building_Slots": 0,
        "Special": False,
    },
    {
        "County_Name": "Bejaia",
        "Barony_Name": "Jijel",
        "Holding_Type": "City",
        "Duchy_Name": "Drylands",
        "Terrain_Type": "domain",
        "Status": "domain",
        "Control": 100,
        "Development": 8,
        "Tax": 0.7,
        "Levies": 78,
        "Buildings_Count": 0,
        "Open_Building_Slots": 0,
        "Special": False,
    },
    {
        "County_Name": "Grand City of Satif",
        "Barony_Name": "Satif",
        "Holding_Type": "Castle",
        "Duchy_Name": "Bejaia",
        "Terrain_Type": "gifted",
        "Status": "gifted",
        "Control": 25,
        "Development": 8,
        "Tax": 0.33,
        "Levies": 195,
        "Buildings_Count": 3,
        "Open_Building_Slots": 2,
        "Special": False,
    },
    {
        "County_Name": "Almeria",
        "Barony_Name": "Almeria",
        "Holding_Type": "Castle",
        "Duchy_Name": "Granada",
        "Terrain_Type": "domain",
        "Status": "domain",
        "Control": 25,
        "Development": 13,
        "Tax": 0.0,
        "Levies": 0,
        "Buildings_Count": 0,
        "Open_Building_Slots": 1,
        "Special": True,
    },
    {
        "County_Name": "Murcia",
        "Barony_Name": "Murcia",
        "Holding_Type": "Castle",
        "Duchy_Name": "Murcia",
        "Terrain_Type": "domain",
        "Status": "domain",
        "Control": 11,
        "Development": 8,
        "Tax": 0.0,
        "Levies": 110,
        "Buildings_Count": 0,
        "Open_Building_Slots": 0,
        "Special": False,
    },
    {
        "County_Name": "Murcia",
        "Barony_Name": "Cartagena",
        "Holding_Type": "City",
        "Duchy_Name": "Murcia",
        "Terrain_Type": "vassal",
        "Status": "vassal",
        "Control": 11,
        "Development": 8,
        "Tax": 0.48,
        "Levies": 79,
        "Buildings_Count": 0,
        "Open_Building_Slots": 0,
        "Special": False,
    },
    {
        "County_Name": "Murcia",
        "Barony_Name": "Caravaca de la Cruz",
        "Holding_Type": "Temple",
        "Duchy_Name": "Murcia",
        "Terrain_Type": "leased",
        "Status": "leased",
        "Control": 11,
        "Development": 8,
        "Tax": 0.43,
        "Levies": 105,
        "Buildings_Count": 0,
        "Open_Building_Slots": 0,
        "Special": False,
    },
    {
        "County_Name": "Sardinia",
        "Barony_Name": "Cagliari",
        "Holding_Type": "Castle",
        "Duchy_Name": "Sardinia",
        "Terrain_Type": "domain",
        "Status": "domain",
        "Control": 10,
        "Development": 10,
        "Tax": 3.95,
        "Levies": 131,
        "Buildings_Count": 0,
        "Open_Building_Slots": 0,
        "Special": True,
    },
    {
        "County_Name": "Sardinia",
        "Barony_Name": "Sassari",
        "Holding_Type": "Castle",
        "Duchy_Name": "Sardinia",
        "Terrain_Type": "domain",
        "Status": "domain",
        "Control": 7,
        "Development": 7,
        "Tax": 1.37,
        "Levies": 119,
        "Buildings_Count": 0,
        "Open_Building_Slots": 1,
        "Special": False,
    },
]


def get_holdings(playthrough_id=None):
    """Return holdings for the selected playthrough.

    This is intentionally seeded for the current phase so the holdings UI is
    usable even before real parquet-backed providers are wired in.
    """
    return list(SEED_HOLDINGS)
